name       : xl2tpd
version    : 1.3.15
release    : 2
source     :
    - https://github.com/xelerance/xl2tpd/archive/v1.3.15.tar.gz : 0d149bf9d2f7d838806e6a36fd7a676d03bf246d2b7869e16c945330e13b922e
license    : GPL-2.0-or-later
component  : network.util
summary    : An implementation of the Layer 2 Tunnelling Protocol
description: |
    xl2tpd is an implementation of the Layer 2 Tunnelling Protocol (RFC 2661).
builddeps  :
    - pkgconfig(libpcap)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
