name       : xl2tpd
version    : 1.3.14
release    : 1
source     :
    - https://github.com/xelerance/xl2tpd/archive/v1.3.14.tar.gz : ff5a0806fecc58c7b9cbc625117a4521c0546522a5f5951ffb6eebdab998610f
license    : GPL-2.0-or-later
component  : network.util
summary    : An implementation of the Layer 2 Tunnelling Protocol
description: |
    xl2tpd is an implementation of the Layer 2 Tunnelling Protocol (RFC 2661).
builddeps  :
    - pkgconfig(libpcap)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
